# Generated by Django 4.0.4 on 2022-07-04 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, null=True)),
                ('imagen', models.ImageField(null=True, upload_to='images/')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('piezas', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadAPagar', models.IntegerField(null=True)),
                ('direccion', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=20)),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('producto', models.ManyToManyField(to='tienda.producto')),
            ],
        ),
    ]
